version: 0.2

phases: 
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew build -x test
artifacts:
  files:
    - build/libs/carrot-clone-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no